import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="my-10 flex flex-col space-y-2">
        <h1 className="mb-10 text-xl font-bold">
          Welcome to Hope's The Mission!
        </h1>
        <Link href="/about">
          <a>
            <div className="border p-2 rounded-lg filter drop-shadow-lg bg-white hover:scale-110 transition-all duration-300">
              <h2 className="text-xl font-bold">About &rarr;</h2>
              <p>About Hope's The Mission</p>
            </div>
          </a>
        </Link>
        <Link href="/posts">
          <a>
            <div className="border p-2 rounded-lg filter drop-shadow-lg bg-white hover:scale-110 transition-all duration-300">
              <h2 className="font-bold text-xl">Blogs &rarr;</h2>
              <p>The wonderful world of blogs</p>
            </div>
          </a>
        </Link>
        <Link href="/events">
          <a>
            <div className="border p-2 rounded-lg filter drop-shadow-lg bg-white hover:scale-110 transition-all duration-300">
              <h2 className="font-bold text-xl">Events &rarr;</h2>
              <p>All the events</p>
            </div>
          </a>
        </Link>

        <Link href="/social">
          <a>
            <div className="border p-2 rounded-lg filter drop-shadow-lg bg-white hover:scale-110 transition-all duration-300">
              <h2 className="font-bold text-xl">Social Media &rarr;</h2>
              <p>Follow me on social media!</p>
            </div>
          </a>
        </Link>
      </section>
    </div>
  );
};

export default Home;
